# FROM node
FROM node:20.9.0-alpine3.18

WORKDIR /frontend_blogapp

# Copy all local files to image.
COPY . .

# When build image:

RUN npm i -g pnpm
RUN pnpm i

CMD ["npm" ,"start"]
EXPOSE 5173

# --------------------------------
# $ cd /frontend
# $ docker build -t frontend .
# $ docker run -p 5173:5173 --name frontend frontend
# $ docker run -d -p 5173:5173 --name frontend frontend
# $ docker run -d -p 80:5173 --name frontend80 qadiradamson/frontend
# Browser: http://localhost:5173
