version: "3.9" # opsiyonel.

services:

    client:
        container_name: frontendblogapp
        image: docker-compose-frontendblogapp
        build: ./client
        ports:
            # dış/iç port numaraları
            - 5173:5173
            - 3000:5173
            - 80:5173
        restart: on-failure # hata anında tekrar çalıştır.
        depends_on:
            # önce aşağıdakileri çalıştır.
            - server # aşağıda tanımlandı.

    server:
        container_name: backendblogapp
        image: docker-compose-backendblogapp
        build: ./server
        ports:
            - 8000:8000
        restart: on-failure
        volumes:
            # fiziksel yollar (external:internal)
            - $PWD/server/logs:/server/logs
            - $PWD/server/upload:/server/upload

# --------------------------------
# $ docker compose up # compose çalıştır.
# $ docker compose up -d --build # compose daemon aç ve tekrar build et.
# $ docker compose down # compose kapat.
# $ docker compose down -v # compose tümünü kapat.
        
